### PR TITLE
Fix testExecuteBatchPreparedStatementFailBulkTypes

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Fixes [#66](https://github.com/crate/crate-alerts/issues/66) and [#348](https://github.com/crate/crate-jdbc/issues/348)
Also added an environment variable for debugging any local distribution.

see https://github.com/crate/crate/commit/2476b1dd1ffd6084f5e77fc2ea2c5d558c323ee9 - before that change `insert into(intcol) values(obj)` 
made `targetType = object` because of higher precedence and `checkSourceAndTargetColsForLengthAndTypesCompatibility` used to caught that `object.isConvertableTo(int) == false` and threw an exception with the old message.

Now `targetType = integer `because of target column higher precedence and `checkSourceAndTargetColsForLengthAndTypesCompatibility` doesn't throw an exception because int is convertible to int and cast exception happens somewhere further -> different exception message unexpected by `testExecuteBatchPreparedStatementFailBulkTypes`

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Review by amotl — APPROVED** [review]
Thank you very much.

**Comment by amotl** [comment]
Apparently, Travis CI is very slow again, if it works at all. We might want to move to GHA, see also #347.

**Comment by amotl** [comment]
> Travis CI is very slow again, if it works at all.

The current Travis CI setup is defunct, see https://github.com/crate/crate-jdbc/issues/347#issuecomment-920983802.

**Review by mfussenegger — APPROVED** [review]

**Comment by BaurzhanSakhariev** [comment]
Hi @amotl, could you please elaborate more on "overrule the checks" - how can I skip Travis step?

**Pull request merged**
