### PR TITLE
Fix UTF-8 encoding

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
## Summary of the changes / Why this is an improvement

- Add compile java encoding option to UTF-8 to avoid encoding error at compilation.

## Checklist

 - [X] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by matriv** [comment]
@OlivierCavadenti Thx! Out of curiosity, have you already encountered an issue, do you have an example?

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Thx! Out of curiosity, have you already encountered an issue, do you have an example?

Yes, I pull the project on Windows, try to run tests and have encoding issues in some files.
I have also some deprecated issues (use of Byte constructor, finalize function, ...) who can prevent building the project on recent version of JDK (I am on Oracle JDK 20).

**Comment by seut** [comment]
@OlivierCavadenti
Thank you for catching this.
I think the root cause for your encoding issues are the usage of `String.format` without defining a `Locale` argument in various test cases. E.g. https://github.com/crate/crate-jdbc/blob/master/driver/test/java/io/crate/client/jdbc/integrationtests/DriverITest.java#L61.
So I'd suggest to solve the root cause instead by replacing all `String.format` occurrences with `String.format(Locale.ENGLISH, ...)`.

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti Thank you for catching this. I think the root cause for your encoding issues are the usage of `String.format` without defining a `Locale` argument in various test cases. E.g. https://github.com/crate/crate-jdbc/blob/master/driver/test/java/io/crate/client/jdbc/integrationtests/DriverITest.java#L61. So I'd suggest to solve the root cause instead by replacing all `String.format` occurrences with `String.format(Locale.ENGLISH, ...)`.

Ok, I will add the Locale but I still have problems with special characters in Java comments.

**Comment by seut** [comment]
> Ok, I will add the Locale

Thank you!

> but I still have problems with special characters in Java comments.

Could the comments be fixed as well? Otherwise lets add the compile encoding flag...

**Comment by seut** [comment]
@OlivierCavadenti 
Do you face any additional issues we could help with?

**Comment by seut** [comment]
I've now reproduced this issue and the problem relates to the `pgjdbc` submodule's source code. 
```
./gradlew test -Dfile.encoding=Cp1252
````
Lets merge what @OlivierCavadenti suggested to fix compilation on systems not defaulting to `UTF-8` file encoding.

**Review by seut — APPROVED** [review]

**Comment by seut** [comment]
@OlivierCavadenti Thank you for this contribution!

**Pull request merged**
