### PR TITLE
upgrad gradle wrapper to 4.8

### PR DESCRIPTION
**Pull request by chaudum**

### CODE REVIEW

**Comment by chaudum** [comment]
@jodok did I assign it to you? :grinning: I think, however, you're totally qualified to review this PR :)

**Comment by mfussenegger** [comment]
@chaudum btw the wrapper.jar usually doesn't have to be updated

**Comment by chaudum** [comment]
@mfussenegger the jar was changed when I ran `gradlew wrapper`

**Comment by mfussenegger** [comment]
> @mfussenegger I was also surprised, but the jar was changed when I ran gradlew wrapper

Yep but it's not really necessary to change it. I think so far there has only been one case where it wasn't compatible with newer versions anymore.

**Pull request merged**
